name: Deploy
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: youtravel

jobs:
  website-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm prod
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: "youtravel/dist/"
          protocol: ftps
          port: ${{ secrets.ftp_port }}
